### ISSUE TITLE
Error message when trying to import *.mdl file

### ISSUE THREAD

**Issue by Aldo5037** [CruzR/Blender-MDL#12]
I Installed the addon using "Install addon" button on the "User Preferences" window, then opened the *.py file for "Blender-MDL"

I enabled the addon on the "Addons" tab in the User Preferences Window.  Now it shows the option "File>Import>WarCraft MDL (.mdl)"

I tried it using file "twilightsparkle.mdl" from "Garry's Mod" downloaded from http://www.equestriadaily.com/2011/07/garys-mod-ponies.html

But got Error output and I got nothing (no vertices, no faces) imported on my scene:

http://gato303co.deviantart.com/art/Blender-Screen-Capture-19-06-2012-309355495

What am I doing wrong?  Is there something missing on my Blender installation?

Thanks for your attention

P.S. my laptop config:
Dell Inspiron 15R N5110, intel core i7, 8GB RAM DDR3, Intel HD Graphics, HD 640GB, Linux Xubuntu 12.04 64bits.

**Comment by CruzR** [comment]
Unfortunately, `.mdl` is a fairly common extension for 3D model formats -- simply because it's a perfect abbreviation for "model". For example, [Quake's model format](http://tfc.duke.free.fr/coding/mdl-specs-en.html) is called `.mdl`, as well as [WarCraft III's model format](https://en.wikipedia.org/wiki/.MDX) and the model format used by the [Source Engine](https://developer.valvesoftware.com/wiki/.mdl). However, although all these formats are called MDL, they are not compatible with each other. This blender plugin is specifically for the WarCraft III MDL format, what you are looking for is a plugin which handles the Source Engine format. Sorry, I can't help you there :( .
